#!/usr/bin/env python3
"""Run deterministic ISM-MICMAC analysis on user-provided judgments.

No survey responses or relationships are generated by this tool. Supply either:

1. A complete Structural Self-Interaction Matrix (SSIM) relation CSV with the
   header ``factor_i,factor_j,relation`` and exactly one row for every unordered
   factor pair. Standard relation symbols are:

   - ``V``: factor_i influences factor_j
   - ``A``: factor_j influences factor_i
   - ``X``: both factors influence each other
   - ``O``: neither factor influences the other

2. A square binary direct-relation matrix CSV. Its first column contains row
   factor names and its remaining headers contain the same factor names, e.g.
   ``factor,<factor 1>,<factor 2>,...``. Cells must be exactly ``0`` or ``1``.

ISM reflexive diagonal links are added by convention. Transitive reachability is
computed with Warshall's algorithm. Level I contains the top-level factors for
which the reachability set equals its intersection with the antecedent set;
those factors are removed and the partition is repeated. MICMAC quadrants are
split at the matrix-derived mean driving and dependence powers.

Example command (both output formats may be requested together)::

    python scripts/ism_micmac.py --input responses.csv --format ssim \
        --json-output results/ism.json --csv-output-dir results/ism_csv

The JSON contains the complete analysis. The CSV directory receives the initial
and final reachability matrices, factor powers/classifications, level
partitions, and transitive links.
"""

from __future__ import annotations

import argparse
import csv
import json
from itertools import combinations
from pathlib import Path
import sys
from typing import Sequence


Matrix = list[list[int]]
_VALID_SSIM_RELATIONS = {"V", "A", "X", "O"}


class InputValidationError(ValueError):
    """Raised when supplied judgments are incomplete or structurally invalid."""


def _read_csv_rows(path: str | Path) -> list[list[str]]:
    source = Path(path)
    if not source.is_file():
        raise InputValidationError(f"input CSV does not exist: {source}")
    try:
        with source.open("r", encoding="utf-8-sig", newline="") as handle:
            rows = [[cell.strip() for cell in row] for row in csv.reader(handle)]
    except (OSError, UnicodeError, csv.Error) as exc:
        raise InputValidationError(f"could not read CSV {source}: {exc}") from exc

    rows = [row for row in rows if any(cell for cell in row)]
    if not rows:
        raise InputValidationError("input CSV is empty")
    return rows


def _check_factor_names(factors: Sequence[str]) -> list[str]:
    cleaned = [factor.strip() for factor in factors]
    if not cleaned or any(not factor for factor in cleaned):
        raise InputValidationError("factor names must be non-empty")
    if len(set(cleaned)) != len(cleaned):
        raise InputValidationError("factor names must be unique")
    folded = [factor.casefold() for factor in cleaned]
    if len(set(folded)) != len(folded):
        raise InputValidationError("factor names must also be unique ignoring case")
    return cleaned


def validate_binary_matrix(factors: Sequence[str], matrix: Sequence[Sequence[int]]) -> Matrix:
    """Validate a square binary matrix and add the conventional reflexive diagonal."""
    clean_factors = _check_factor_names(factors)
    size = len(clean_factors)
    if len(matrix) != size:
        raise InputValidationError(
            f"matrix has {len(matrix)} rows but {size} factors were supplied"
        )

    validated: Matrix = []
    for row_index, row in enumerate(matrix):
        if len(row) != size:
            raise InputValidationError(
                f"matrix row {row_index + 1} has {len(row)} cells; expected {size}"
            )
        validated_row: list[int] = []
        for column_index, value in enumerate(row):
            if isinstance(value, bool):
                value = int(value)
            if value not in (0, 1):
                raise InputValidationError(
                    f"matrix cell ({row_index + 1}, {column_index + 1}) must be 0 or 1"
                )
            validated_row.append(int(value))
        validated.append(validated_row)

    for index in range(size):
        validated[index][index] = 1
    return validated


def load_ssim_csv(path: str | Path) -> tuple[list[str], Matrix]:
    """Load a complete pairwise SSIM CSV without filling missing judgments."""
    rows = _read_csv_rows(path)
    normalized_header = [cell.casefold() for cell in rows[0]]
    expected_header = ["factor_i", "factor_j", "relation"]
    if normalized_header != expected_header:
        raise InputValidationError(
            "SSIM header must be exactly: factor_i,factor_j,relation"
        )
    if len(rows) == 1:
        raise InputValidationError("SSIM contains no user-provided relation rows")

    factors: list[str] = []
    judgments: dict[frozenset[str], tuple[str, str, str]] = {}
    for csv_row_number, row in enumerate(rows[1:], start=2):
        if len(row) != 3:
            raise InputValidationError(
                f"SSIM row {csv_row_number} has {len(row)} cells; expected 3"
            )
        factor_i, factor_j, relation = row[0], row[1], row[2].upper()
        if not factor_i or not factor_j:
            raise InputValidationError(
                f"SSIM row {csv_row_number} has an empty factor name"
            )
        if factor_i.casefold() == factor_j.casefold():
            raise InputValidationError(
                f"SSIM row {csv_row_number} relates a factor to itself"
            )
        if relation not in _VALID_SSIM_RELATIONS:
            allowed = ", ".join(sorted(_VALID_SSIM_RELATIONS))
            raise InputValidationError(
                f"SSIM row {csv_row_number} has relation {relation!r}; expected {allowed}"
            )

        for factor in (factor_i, factor_j):
            if factor not in factors:
                if any(existing.casefold() == factor.casefold() for existing in factors):
                    raise InputValidationError(
                        "factor names must be unique ignoring case"
                    )
                factors.append(factor)

        pair_key = frozenset((factor_i, factor_j))
        if pair_key in judgments:
            raise InputValidationError(
                f"duplicate SSIM judgment for pair {factor_i!r}, {factor_j!r}"
            )
        judgments[pair_key] = (factor_i, factor_j, relation)

    factors = _check_factor_names(factors)
    missing_pairs = [
        (factor_i, factor_j)
        for factor_i, factor_j in combinations(factors, 2)
        if frozenset((factor_i, factor_j)) not in judgments
    ]
    if missing_pairs:
        rendered = ", ".join(f"({a}, {b})" for a, b in missing_pairs[:10])
        suffix = " ..." if len(missing_pairs) > 10 else ""
        raise InputValidationError(
            f"SSIM is incomplete; missing {len(missing_pairs)} pair judgment(s): "
            f"{rendered}{suffix}"
        )

    index = {factor: position for position, factor in enumerate(factors)}
    matrix: Matrix = [[0 for _ in factors] for _ in factors]
    for position in range(len(factors)):
        matrix[position][position] = 1

    for factor_i, factor_j, relation in judgments.values():
        i, j = index[factor_i], index[factor_j]
        if relation in {"V", "X"}:
            matrix[i][j] = 1
        if relation in {"A", "X"}:
            matrix[j][i] = 1

    return factors, validate_binary_matrix(factors, matrix)


def load_matrix_csv(path: str | Path) -> tuple[list[str], Matrix]:
    """Load a labeled square binary direct-relation matrix CSV."""
    rows = _read_csv_rows(path)
    if len(rows[0]) < 2:
        raise InputValidationError(
            "matrix header must contain a row-label column and at least one factor"
        )
    factors = _check_factor_names(rows[0][1:])
    size = len(factors)
    if len(rows) != size + 1:
        raise InputValidationError(
            f"matrix has {len(rows) - 1} data rows; expected {size}"
        )

    row_values: dict[str, list[int]] = {}
    for csv_row_number, row in enumerate(rows[1:], start=2):
        if len(row) != size + 1:
            raise InputValidationError(
                f"matrix row {csv_row_number} has {len(row) - 1} values; expected {size}"
            )
        row_factor = row[0]
        if row_factor not in factors:
            raise InputValidationError(
                f"matrix row {csv_row_number} has unknown row factor {row_factor!r}"
            )
        if row_factor in row_values:
            raise InputValidationError(f"duplicate matrix row for factor {row_factor!r}")

        values: list[int] = []
        for column_index, raw_value in enumerate(row[1:], start=1):
            if raw_value not in {"0", "1"}:
                raise InputValidationError(
                    f"matrix cell ({row_factor}, {factors[column_index - 1]}) "
                    f"must be exactly 0 or 1"
                )
            values.append(int(raw_value))
        row_values[row_factor] = values

    missing_rows = [factor for factor in factors if factor not in row_values]
    if missing_rows:
        raise InputValidationError(
            f"matrix is missing rows for: {', '.join(missing_rows)}"
        )
    ordered_matrix = [row_values[factor] for factor in factors]
    return factors, validate_binary_matrix(factors, ordered_matrix)


def load_input_csv(
    path: str | Path,
    input_format: str = "auto",
) -> tuple[list[str], Matrix]:
    """Load SSIM or matrix input, optionally detecting format from its header."""
    if input_format not in {"auto", "ssim", "matrix"}:
        raise InputValidationError("format must be one of: auto, ssim, matrix")
    selected_format = input_format
    if selected_format == "auto":
        header = [cell.casefold() for cell in _read_csv_rows(path)[0]]
        selected_format = (
            "ssim"
            if header == ["factor_i", "factor_j", "relation"]
            else "matrix"
        )
    if selected_format == "ssim":
        return load_ssim_csv(path)
    return load_matrix_csv(path)


def transitive_reachability(matrix: Sequence[Sequence[int]]) -> Matrix:
    """Return the reflexive transitive closure using Warshall's algorithm."""
    factors = [str(index) for index in range(len(matrix))]
    closure = validate_binary_matrix(factors, matrix)
    size = len(closure)
    for intermediate in range(size):
        for source in range(size):
            if closure[source][intermediate] == 0:
                continue
            for target in range(size):
                if closure[intermediate][target]:
                    closure[source][target] = 1
    return closure


def driving_dependence_powers(matrix: Sequence[Sequence[int]]) -> tuple[list[int], list[int]]:
    """Compute MICMAC driving (row sum) and dependence (column sum) powers."""
    factors = [str(index) for index in range(len(matrix))]
    validated = validate_binary_matrix(factors, matrix)
    driving = [sum(row) for row in validated]
    dependence = [sum(validated[row][column] for row in range(len(validated)))
                  for column in range(len(validated))]
    return driving, dependence


def partition_levels(
    factors: Sequence[str],
    final_reachability: Sequence[Sequence[int]],
) -> list[dict[str, object]]:
    """Partition factors into standard ISM levels, with top outcomes at Level I."""
    clean_factors = _check_factor_names(factors)
    matrix = validate_binary_matrix(clean_factors, final_reachability)
    remaining = list(range(len(clean_factors)))
    partitions: list[dict[str, object]] = []
    level = 1

    while remaining:
        selected: list[int] = []
        details: list[dict[str, object]] = []
        for factor_index in remaining:
            reachability = {
                target for target in remaining if matrix[factor_index][target]
            }
            antecedent = {
                source for source in remaining if matrix[source][factor_index]
            }
            intersection = reachability & antecedent
            if reachability == intersection:
                selected.append(factor_index)
                details.append(
                    {
                        "factor": clean_factors[factor_index],
                        "reachability_set": [clean_factors[i] for i in remaining if i in reachability],
                        "antecedent_set": [clean_factors[i] for i in remaining if i in antecedent],
                        "intersection_set": [clean_factors[i] for i in remaining if i in intersection],
                    }
                )

        if not selected:
            raise ArithmeticError("ISM level partition made no progress")
        partitions.append(
            {
                "level": level,
                "factors": [clean_factors[index] for index in selected],
                "details": details,
            }
        )
        selected_set = set(selected)
        remaining = [index for index in remaining if index not in selected_set]
        level += 1

    return partitions


def _micmac_classification(
    driving_power: int,
    dependence_power: int,
    driving_threshold: float,
    dependence_threshold: float,
) -> str:
    high_driving = driving_power >= driving_threshold
    high_dependence = dependence_power >= dependence_threshold
    if not high_driving and not high_dependence:
        return "autonomous"
    if not high_driving and high_dependence:
        return "dependent"
    if high_driving and high_dependence:
        return "linkage"
    return "independent"


def analyze_ism_micmac(
    factors: Sequence[str],
    initial_matrix: Sequence[Sequence[int]],
) -> dict[str, object]:
    """Compute complete ISM-MICMAC results from validated user relationships."""
    clean_factors = _check_factor_names(factors)
    initial = validate_binary_matrix(clean_factors, initial_matrix)
    final = transitive_reachability(initial)
    driving, dependence = driving_dependence_powers(final)
    levels = partition_levels(clean_factors, final)

    driving_threshold = sum(driving) / len(driving)
    dependence_threshold = sum(dependence) / len(dependence)
    level_by_factor = {
        factor: partition["level"]
        for partition in levels
        for factor in partition["factors"]
    }

    factor_analysis: list[dict[str, object]] = []
    for index, factor in enumerate(clean_factors):
        factor_analysis.append(
            {
                "factor": factor,
                "level": level_by_factor[factor],
                "driving_power": driving[index],
                "dependence_power": dependence[index],
                "micmac_classification": _micmac_classification(
                    driving[index],
                    dependence[index],
                    driving_threshold,
                    dependence_threshold,
                ),
                "reachability_set": [
                    clean_factors[target]
                    for target in range(len(clean_factors))
                    if final[index][target]
                ],
                "antecedent_set": [
                    clean_factors[source]
                    for source in range(len(clean_factors))
                    if final[source][index]
                ],
            }
        )

    transitive_links = [
        {"from": clean_factors[source], "to": clean_factors[target]}
        for source in range(len(clean_factors))
        for target in range(len(clean_factors))
        if initial[source][target] == 0 and final[source][target] == 1
    ]

    return {
        "method": "Deterministic ISM-MICMAC analysis of user-provided relationships",
        "method_notes": [
            "No relationships or survey responses are generated or imputed.",
            "Reflexive diagonal links are added by the standard ISM convention.",
            "Final reachability is the transitive closure of the submitted direct relationships.",
            "MICMAC low/high quadrants are split at the mean powers computed from this final matrix.",
        ],
        "factors": clean_factors,
        "initial_reachability_matrix": initial,
        "final_reachability_matrix": final,
        "transitive_links_added": transitive_links,
        "level_partitions": levels,
        "micmac_thresholds": {
            "driving_power_mean": driving_threshold,
            "dependence_power_mean": dependence_threshold,
            "high_rule": "power >= matrix mean",
        },
        "factor_analysis": factor_analysis,
    }


def write_json_report(result: dict[str, object], path: str | Path) -> Path:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8") as handle:
        json.dump(result, handle, indent=2, ensure_ascii=False)
        handle.write("\n")
    return destination


def _write_matrix_csv(path: Path, factors: Sequence[str], matrix: Sequence[Sequence[int]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["factor", *factors])
        for factor, row in zip(factors, matrix):
            writer.writerow([factor, *row])


def write_csv_reports(result: dict[str, object], output_dir: str | Path) -> list[Path]:
    """Write complete analysis tables as interoperable CSV files."""
    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)
    factors = result["factors"]

    initial_path = destination / "initial_reachability.csv"
    final_path = destination / "final_reachability.csv"
    factor_path = destination / "factor_analysis.csv"
    level_path = destination / "level_partitions.csv"
    links_path = destination / "transitive_links.csv"

    _write_matrix_csv(initial_path, factors, result["initial_reachability_matrix"])
    _write_matrix_csv(final_path, factors, result["final_reachability_matrix"])

    with factor_path.open("w", encoding="utf-8", newline="") as handle:
        fieldnames = [
            "factor",
            "level",
            "driving_power",
            "dependence_power",
            "micmac_classification",
            "reachability_set",
            "antecedent_set",
        ]
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in result["factor_analysis"]:
            writer.writerow(
                {
                    **row,
                    "reachability_set": "|".join(row["reachability_set"]),
                    "antecedent_set": "|".join(row["antecedent_set"]),
                }
            )

    with level_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["level", "factors"])
        for partition in result["level_partitions"]:
            writer.writerow([partition["level"], "|".join(partition["factors"])])

    with links_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=["from", "to"])
        writer.writeheader()
        writer.writerows(result["transitive_links_added"])

    return [initial_path, final_path, factor_path, level_path, links_path]


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Compute ISM transitive reachability, levels, and MICMAC powers from "
            "real user-provided SSIM judgments or a binary relation matrix."
        )
    )
    parser.add_argument("--input", required=True, help="Path to the input CSV.")
    parser.add_argument(
        "--format",
        choices=("auto", "ssim", "matrix"),
        default="auto",
        help="Input format; auto detects the exact SSIM header (default: auto).",
    )
    parser.add_argument(
        "--json-output",
        help="Optional JSON report path. If no output option is given, JSON is printed.",
    )
    parser.add_argument(
        "--csv-output-dir",
        help="Optional directory for reachability, level, link, and factor CSV files.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        factors, matrix = load_input_csv(args.input, args.format)
        result = analyze_ism_micmac(factors, matrix)
        if args.json_output:
            write_json_report(result, args.json_output)
        if args.csv_output_dir:
            write_csv_reports(result, args.csv_output_dir)
        if not args.json_output and not args.csv_output_dir:
            json.dump(result, sys.stdout, indent=2, ensure_ascii=False)
            sys.stdout.write("\n")
    except (InputValidationError, ArithmeticError, OSError) as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
