[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$InstallRoot = Split-Path -Parent $PSScriptRoot
$Executable = Join-Path $InstallRoot 'EWasteManagement.exe'

function Fail([string]$Message) {
    Write-Host "ERROR: $Message" -ForegroundColor Red
    exit 1
}

if ([string]::IsNullOrWhiteSpace($env:LOCALAPPDATA)) {
    Fail 'LOCALAPPDATA is unavailable for this Windows user.'
}
$StateRoot = Join-Path $env:LOCALAPPDATA 'EWasteManagement'
$ConfigDirectory = Join-Path $StateRoot 'config'
$ConfigPath = Join-Path $ConfigDirectory '.env'

function ConvertTo-DotEnvLine([string]$Name, [string]$Value) {
    if ($Value.Contains("`r") -or $Value.Contains("`n")) {
        throw "$Name cannot contain a newline."
    }
    $Escaped = $Value.Replace('\', '\\').Replace('"', '\"')
    return "$Name=`"$Escaped`""
}

if (-not (Test-Path -LiteralPath $Executable -PathType Leaf)) {
    Fail "EWasteManagement.exe was not found beside the release scripts: $InstallRoot"
}

Write-Host 'E-Waste Management localhost configuration' -ForegroundColor Cyan
Write-Host 'Use a Clerk DEVELOPMENT instance. Localhost must use a key beginning pk_test_.'
Write-Host 'The publishable key and JWKS URL are public identifiers; never paste a Clerk secret key.'
Write-Host ''

$PublishableKey = (Read-Host 'Clerk publishable key (pk_test_)').Trim()
if (-not $PublishableKey.StartsWith('pk_test_')) {
    Fail 'The publishable key must begin with pk_test_. pk_live_ is not valid for localhost.'
}
if ($PublishableKey -match '(?i)(example|your-clerk|replace-with)') {
    Fail 'The publishable key still looks like a placeholder.'
}

$JwksUrl = (Read-Host 'Clerk HTTPS JWKS URL').Trim()
[Uri]$ParsedJwks = $null
if (-not [Uri]::TryCreate($JwksUrl, [UriKind]::Absolute, [ref]$ParsedJwks)) {
    Fail 'The JWKS URL is not a valid absolute URL.'
}
if ($ParsedJwks.Scheme -ne 'https' -or $JwksUrl -notmatch '(?i)jwks') {
    Fail 'The JWKS URL must be HTTPS and identify the Clerk JWKS endpoint.'
}
if ($JwksUrl -match '(?i)(example|your-clerk|replace-with)') {
    Fail 'The JWKS URL still looks like a placeholder.'
}

$Issuer = (Read-Host 'Optional exact Clerk issuer (press Enter to omit)').Trim()
$Audience = (Read-Host 'Optional exact Clerk audience (press Enter to omit)').Trim()

New-Item -ItemType Directory -Force -Path $ConfigDirectory | Out-Null
if (Test-Path -LiteralPath $ConfigPath -PathType Leaf) {
    $Timestamp = Get-Date -Format 'yyyyMMdd-HHmmss'
    Copy-Item -LiteralPath $ConfigPath -Destination "$ConfigPath.before-$Timestamp" -Force
    [string[]]$Lines = Get-Content -LiteralPath $ConfigPath
} else {
    [string[]]$Lines = @(
        '# E-Waste Management per-user localhost configuration',
        '# Generated by Configure E-Waste.cmd'
    )
}

function Set-ConfigValue([string]$Name, [string]$Value, [bool]$KeepWhenEmpty) {
    $Pattern = '^\s*' + [Regex]::Escape($Name) + '\s*='
    $script:Lines = @($script:Lines | Where-Object { $_ -notmatch $Pattern })
    if ($KeepWhenEmpty -or -not [string]::IsNullOrWhiteSpace($Value)) {
        $script:Lines += ConvertTo-DotEnvLine $Name $Value
    }
}

Set-ConfigValue 'EWASTE_CLERK_PUBLISHABLE_KEY' $PublishableKey $true
Set-ConfigValue 'CLERK_JWKS_URL' $JwksUrl $true
Set-ConfigValue 'CLERK_ISSUER' $Issuer $false
Set-ConfigValue 'CLERK_AUDIENCE' $Audience $false
Set-ConfigValue 'ALLOWED_ORIGINS' 'http://127.0.0.1:8000' $true
Set-ConfigValue 'EWASTE_MODEL' 'siglip2-base' $true
Set-ConfigValue 'HF_HUB_OFFLINE' '1' $true

$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[IO.File]::WriteAllText($ConfigPath, (($Lines -join "`r`n") + "`r`n"), $Utf8NoBom)
Write-Host ''
Write-Host "Configuration saved under $ConfigDirectory" -ForegroundColor Green
Write-Host 'Existing unrelated settings (including DELETE_API_KEY, if present) were preserved.'
Write-Host ''

& $Executable doctor
if ($LASTEXITCODE -ne 0) {
    Write-Host ''
    Write-Host 'Configuration was saved, but diagnostics found another release prerequisite problem.' -ForegroundColor Yellow
    exit $LASTEXITCODE
}
Write-Host ''
Write-Host 'Configuration and packaged assets are ready. Run Start E-Waste.cmd.' -ForegroundColor Green
exit 0
